# Generated by Django 4.1.1 on 2022-11-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('words', models.IntegerField()),
                ('chars', models.IntegerField()),
                ('vowels', models.IntegerField()),
                ('consonants', models.IntegerField()),
            ],
        ),
    ]
